kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/server

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
  - name: lint&format
    image: rust:latest
    commands:
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo clippy
      - cargo clippy -- -D warnings
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo clippy --fix
      - cargo fmt --all -- --check
      - cargo fmt --all
  - name: build
    image: rust:latest
    commands:
      - cargo build --release
