kind: pipeline
type: exec
name: web

platform:
  os: windows
  arch: amd64

trigger:
  branch:
    include:
      - main
      - dev
    event:
      - push
      - pull_request

steps:
  - name: prepare
    commands:
      - cd apps/web
  - name: lint
    commands:
      - cd apps/web
      - pnpm install
      - pnpm run lint
      - pnpm run lint:fix
  - name: format
    commands:
      - cd apps/web
      - pnpm run format
  - name: build
    commands:
      - cd apps/web
      - pnpm run build

---
kind: pipeline
type: exec
name: server

platform:
  os: windows
  arch: amd64

steps:
  - name: clippy
    commands:
      - cargo clippy -- -D warnings
      - cargo clippy --all-targets --all-features -- -D
      - cargo clippy --fix
  - name: fmt
    commands:
      - cargo fmt --all -- --check
      - cargo fmt --all
  - name: build
    commands:
      - cargo build --release
