kind: pipeline
type: docker
name: web

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/gd-web

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.pnpm-store

  - name: install
    image: node:20.10.0
    volumes:
      - name: node_modules
        path: /drone/gd-web/node_modules
    commands:
      - corepack enable
      - pnpm config set store-dir .pnpm-store
      - pnpm install

  - name: lint
    image: node:20.10.0
    volumes:
      - name: node_modules
        path: /drone/gd-web/node_modules
    commands:
      - pnpm run lint
      - pnpm run lint:fix

  - name: format
    image: node:20.10.0
    volumes:
      - name: node_modules
        path: /drone/gd-web/node_modules
    commands:
      - pnpm run format

  - name: build
    image: node:20.10.0
    volumes:
      - name: node_modules
        path: /drone/gd-web/node_modules
    commands:
      - pnpm run build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.pnpm-store

volumes:
  - name: cache
    host:
      path: /tmp/drone/gd-web/cache
