kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare rust
    image: rust:latest
    commands:
      - rustup component add clippy
      - rustup component add rustfmt
  - name: lint
    depends_on: [prepare]
    commands:
      - cargo clippy
      - cargo clippy -- -D warnings
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo clippy --fix
  - name: format
    depends_on: [prepare]
    commands:
      - cargo fmt --all -- --check
      - cargo fmt --all
  - name: test
    depends_on: [prepare]
    commands:
      - cargo test
  - name: build
    depends_on: [prepare]
    commands:
      - cargo build --release
