kind: pipeline
type: docker
name: web

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: lint&format
    image: node:20.10.0
    commands:
      - npm install -g pnpm
      - pnpm install
      - pnpm run lint
      - pnpm run lint:fix
      - pnpm run format
  - name: build
    image: node:20.10.0
    commands:
      - npm install -g pnpm
      - pnpm install
      - pnpm run build
