//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod alert_information;
pub mod analysis;
pub mod enforcement_records;
pub mod farms;
pub mod harvest_records;
pub mod operation_logs;
pub mod penalty_records;
pub mod pesticide_residue_detection_records;
pub mod pesticide_usage_records;
pub mod planting_records;
pub mod product_inspection_records;
pub mod quality_feedback;
pub mod query_logs;
pub mod report;
pub mod risk_assessment;
pub mod seeds;
pub mod statistical_data;
pub mod users;
