//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logistics_warehouse")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub warehouse_id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    pub address: String,
    pub phone: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::logistics_transport::Entity")]
    LogisticsTransport,
}

impl Related<super::logistics_transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogisticsTransport.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
