//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "penalty_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub penalty_record_id: i32,
    pub penalty_date: Date,
    pub farm_id: i32,
    pub penalty_type: String,
    pub penalty_amount: Decimal,
    #[sea_orm(column_type = "Text")]
    pub penalty_reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::farms::Entity",
        from = "Column::FarmId",
        to = "super::farms::Column::FarmId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Farms,
}

impl Related<super::farms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Farms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
