//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "planting_seed")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub seed_id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    pub r#type: String,
    pub number: i32,
    pub unit: String,
    pub price: Decimal,
    pub description: String,
    pub source: String,
    pub supplier: String,
    pub purchase_date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
