//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "planting_pesticide_use")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub pesticide_use_id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub crops: String,
    pub name: String,
    pub r#type: String,
    pub number: i32,
    pub unit: String,
    pub price: Decimal,
    pub description: String,
    pub source: String,
    pub supplier: String,
    pub apply_at: Date,
    pub application_method: String,
    pub quantity: Decimal,
    pub employee_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::planting_employee::Entity",
        from = "Column::EmployeeId",
        to = "super::planting_employee::Column::EmployeeId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PlantingEmployee,
}

impl Related<super::planting_employee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlantingEmployee.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
