//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "planting_crop_monitoring")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub crop_monitoring_id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    pub crop: String,
    pub soil_moisture: Decimal,
    pub soil_temperature: Decimal,
    pub air_humidity: Decimal,
    pub air_temperature: Decimal,
    pub light_intensity: Decimal,
    pub carbon_dioxide: Decimal,
    pub monitor_at: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
