//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::alert_information::Entity as AlertInformation;
pub use super::analysis::Entity as Analysis;
pub use super::enforcement_records::Entity as EnforcementRecords;
pub use super::farms::Entity as Farms;
pub use super::harvest_records::Entity as HarvestRecords;
pub use super::operation_logs::Entity as OperationLogs;
pub use super::penalty_records::Entity as PenaltyRecords;
pub use super::pesticide_residue_detection_records::Entity as PesticideResidueDetectionRecords;
pub use super::pesticide_usage_records::Entity as PesticideUsageRecords;
pub use super::planting_records::Entity as PlantingRecords;
pub use super::product_inspection_records::Entity as ProductInspectionRecords;
pub use super::quality_feedback::Entity as QualityFeedback;
pub use super::query_logs::Entity as QueryLogs;
pub use super::report::Entity as Report;
pub use super::risk_assessment::Entity as RiskAssessment;
pub use super::seeds::Entity as Seeds;
pub use super::statistical_data::Entity as StatisticalData;
pub use super::users::Entity as Users;
