//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processing_step")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub step_id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    pub required_raw_material: String,
    pub processing_method: String,
    pub processing_at: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
