//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "employee")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    pub age: i32,
    pub part: String,
    pub position: String,
    pub phone: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::harvest::Entity")]
    Harvest,
    #[sea_orm(has_many = "super::pesticide::Entity")]
    Pesticide,
}

impl Related<super::harvest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Harvest.def()
    }
}

impl Related<super::pesticide::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pesticide.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
